BEGIN IMMEDIATE;
CREATE TABLE uploads(id TEXT PRIMARY KEY,owner TEXT NOT NULL,name TEXT NOT NULL,mime TEXT NOT NULL,size INTEGER NOT NULL,received INTEGER NOT NULL DEFAULT 0,expires INTEGER NOT NULL);
CREATE TABLE upload_chunks(upload_id TEXT NOT NULL REFERENCES uploads(id) ON DELETE CASCADE,offset INTEGER NOT NULL,data BLOB NOT NULL,PRIMARY KEY(upload_id,offset));
CREATE TABLE job_uploads(job_id TEXT PRIMARY KEY REFERENCES jobs(id),upload_id TEXT NOT NULL REFERENCES uploads(id));
CREATE TABLE upload_policy(id INTEGER PRIMARY KEY CHECK(id=1),body TEXT NOT NULL);
PRAGMA user_version=9;
COMMIT;
